### ISSUE TITLE
typo in pattern names

### ISSUE THREAD

**Issue by FeLungs** [adlnet/MasterObjectModel#3]
`https://w3id.org/xapi/tla#passed_session`
https://github.com/adlnet/MasterObjectModel/blob/288aa8537ae0e734f2726ce04bc9070f3acc2f4a/MOM_0_13_0.json#L2963

`https://w3id.org/xapi/tla#failed_session`
https://github.com/adlnet/MasterObjectModel/blob/288aa8537ae0e734f2726ce04bc9070f3acc2f4a/MOM_0_13_0.json#L2978

**Comment by vbhayden** [comment]
Thanks for picking these up!  We'll get these corrected sometime this week.

-Trey

**Comment by FeLungs** [comment]
np, as an FYI I created a branch with the revisions applied but I'm unable to push / create a PR.

**Comment by vbhayden** [comment]
Hmmm that's odd, don't think there should be an issue with PRs.  Let me check that.

**Comment by vbhayden** [comment]
Oh I see, so go ahead and fork the repo to your account.  That should enable GitHub to see it and allow you to submit the PR.  If you already have it forked, then it might be private as I can't view it on your profile etc.
